// @ts-nocheck
import React from 'react';
import type { CaptionSource, CaptionSegment } from '@sound/shared';
import { parseSRT, parseVTT, splitTextToSegments } from '../../../utils/captionsParsers';

export interface Step4CaptionsProps {
  t: any;
  captionsEnabled: boolean;
  setCaptionsEnabled: (v: boolean) => void;
  captionSource: CaptionSource;
  setCaptionSource: (v: CaptionSource) => void;
  captionRawText: string;
  setCaptionRawText: (v: string) => void;
  captionSegments: CaptionSegment[];
  setCaptionSegments: (v: CaptionSegment[]) => void;
  captionFileRef: React.RefObject<HTMLInputElement>;
  captionUploadedFile: string;
  setCaptionUploadedFile: (v: string) => void;
  scriptText: string;
  captionLang: string;
  setCaptionLang: (v: string) => void;
  captionLangOpen: boolean;
  setCaptionLangOpen: (v: boolean) => void;
  LANGUAGES: any[];
  captionStyle: 'standard' | 'karaoke' | 'subtitles';
  setCaptionStyle: (v: 'standard' | 'karaoke' | 'subtitles') => void;
  setStep: (step: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12) => void;
  iconPrev: string;
  saveDraft: (step: number) => void;
  saving: boolean;
}

export function Step4Captions({
  t, captionsEnabled, setCaptionsEnabled, captionSource, setCaptionSource,
  captionRawText, setCaptionRawText, captionSegments, setCaptionSegments,
  captionFileRef, captionUploadedFile, setCaptionUploadedFile, scriptText,
  captionLang, setCaptionLang, captionLangOpen, setCaptionLangOpen, LANGUAGES,
  captionStyle, setCaptionStyle, setStep, iconPrev, saveDraft, saving
}: Step4CaptionsProps) {
  return (
    <section className="acp-section">
      <h1 className="acp-section__title">
        <span className="material-symbols-outlined" aria-hidden="true">subtitles</span>
        {t('captionsSetup', 'إعداد الترجمة والنصوص')}
        <span className="acp-badge acp-badge--optional">{t('optional', 'اختياري')}</span>
      </h1>
      <div className="acp-form">
        <label className="acp-label acp-label--row acp-toggle-main">
          <input type="checkbox" checked={captionsEnabled} onChange={(e) => setCaptionsEnabled(e.target.checked)} />
          <span>{t('enableCaptions', 'تفعيل النصوص / الترجمة')}</span>
        </label>
        {captionsEnabled && (
          <>
            <label className="acp-label">{t('captionSource', 'مصدر النص')}</label>
            <div className="acp-chips">
              {([
                { k: 'manual' as CaptionSource, l: t('manualInput', 'كتابة يدوية'), icon: 'edit_note' },
                { k: 'uploaded' as CaptionSource, l: t('uploadFile', 'رفع ملف'), icon: 'upload_file' },
                { k: 'autoCue' as CaptionSource, l: t('importFromPrompter', 'استيراد من الملقن'), icon: 'teleprompter' },
                { k: 'generated' as CaptionSource, l: t('autoGenerated', 'توليد تلقائي'), icon: 'auto_awesome' },
              ]).map((s) => (
                <button
                  key={s.k}
                  className={`acp-chip ${captionSource === s.k ? 'acp-chip--selected' : ''} ${s.k === 'generated' ? 'acp-chip--disabled' : ''}`}
                  onClick={() => s.k !== 'generated' && setCaptionSource(s.k)}
                  type="button"
                  disabled={s.k === 'generated'}
                >
                  <span className="material-symbols-outlined acp-chip__icon">{s.icon}</span>
                  {s.l}
                  {s.k === 'generated' && <span className="acp-badge acp-badge--soon">{t('soon', 'قريباً')}</span>}
                </button>
              ))}
            </div>

            {captionSource === 'manual' && (
              <div className="acp-captions-editor">
                <label className="acp-label">{t('writeCaptionText', 'اكتب النص (كل سطر = مقطع واحد)')}</label>
                <textarea
                  className="acp-textarea acp-textarea--captions"
                  rows={8}
                  dir="auto"
                  placeholder={t('captionPlaceholder', 'اكتب النص هنا...\nكل سطر سيصبح مقطع منفصل')}
                  value={captionRawText}
                  onChange={(e) => {
                    setCaptionRawText(e.target.value);
                    setCaptionSegments(splitTextToSegments(e.target.value));
                  }}
                />
                {captionSegments.length > 0 && (
                  <p className="acp-hint">
                    <span className="material-symbols-outlined acp-hint__icon">segment</span>
                    {captionSegments.length} {t('segmentNoTiming', 'مقطع — بدون توقيت (نص غير متزامن)')}
                  </p>
                )}
              </div>
            )}

            {captionSource === 'uploaded' && (
              <div className="acp-captions-editor">
                <label className="acp-label">{t('uploadSubtitleFile', 'ارفع ملف ترجمة (SRT أو VTT)')}</label>
                <input
                  ref={captionFileRef}
                  type="file"
                  accept=".srt,.vtt"
                  className="acp-file-input"
                  onChange={(e) => {
                    const file = e.target.files?.[0];
                    if (!file) return;
                    setCaptionUploadedFile(file.name);
                    const reader = new FileReader();
                    reader.onload = () => {
                      const text = reader.result as string;
                      setCaptionRawText(text);
                      const ext = file.name.toLowerCase();
                      if (ext.endsWith('.srt')) {
                        setCaptionSegments(parseSRT(text));
                      } else if (ext.endsWith('.vtt')) {
                        setCaptionSegments(parseVTT(text));
                      } else {
                        setCaptionSegments(splitTextToSegments(text));
                      }
                    };
                    reader.readAsText(file);
                  }}
                />
                {captionUploadedFile && (
                  <p className="acp-hint">
                    <span className="material-symbols-outlined acp-hint__icon">description</span>
                    {captionUploadedFile}
                  </p>
                )}
                {captionSegments.length > 0 && (
                  <div className="acp-captions-preview">
                    <p className="acp-hint">
                      <span className="material-symbols-outlined acp-hint__icon">segment</span>
                      {captionSegments.length} {t('segment', 'مقطع')}
                      {captionSegments[0]?.startMs !== undefined ? t('withTiming', ' — مع توقيت') : t('withoutTiming', ' — بدون توقيت')}
                    </p>
                    <div className="acp-captions-preview__list">
                      {captionSegments.slice(0, 5).map((seg) => (
                        <div key={seg.id} className="acp-captions-preview__seg">
                          {seg.startMs !== undefined && (
                            <span className="acp-captions-preview__time">
                              {Math.floor(seg.startMs / 1000)}s
                            </span>
                          )}
                          <span className="acp-captions-preview__text">{seg.text}</span>
                        </div>
                      ))}
                      {captionSegments.length > 5 && (
                        <p className="acp-hint">{t('andMoreSegments', `و${captionSegments.length - 5} مقطع آخر...`)}</p>
                      )}
                    </div>
                  </div>
                )}
              </div>
            )}

            {captionSource === 'autoCue' && (
              <div className="acp-captions-editor">
                {scriptText ? (
                  <>
                    <p className="acp-hint">
                      <span className="material-symbols-outlined acp-hint__icon">teleprompter</span>
                      {t('youCanImportPrompterText', 'يمكنك استيراد نص الملقن كنص ترجمة')}
                    </p>
                    <button
                      className="acp-btn acp-btn--ghost"
                      type="button"
                      onClick={() => {
                        setCaptionRawText(scriptText);
                        setCaptionSegments(splitTextToSegments(scriptText));
                      }}
                    >
                      <span className="material-symbols-outlined">content_copy</span>
                      {t('importPrompterText', 'استيراد نص الملقن')}
                    </button>
                    {captionSegments.length > 0 && (
                      <p className="acp-hint">
                        <span className="material-symbols-outlined acp-hint__icon">check_circle</span>
                        {t('imported', 'تم استيراد')} {captionSegments.length} {t('segmentsNoTiming', 'مقطع (بدون توقيت)')}
                      </p>
                    )}
                  </>
                ) : (
                  <p className="acp-hint">
                    <span className="material-symbols-outlined acp-hint__icon">info</span>
                    {t('noPrompterTextFound', 'لا يوجد نص ملقن. أضف نص الملقن في الخطوة 5 أولاً.')}
                  </p>
                )}
              </div>
            )}

            {captionSource === 'generated' && (
              <div className="acp-captions-editor">
                <p className="acp-hint">
                  <span className="material-symbols-outlined acp-hint__icon">auto_awesome</span>
                  {t('soonNeedsVoiceProvider', 'قريباً — يتطلب مزود تفريغ صوتي')}
                </p>
              </div>
            )}

            <div className="acp-label">
              {t('textLanguage', 'لغة النص')}
              <div className="acp-glass-dropdown">
                <button className="acp-glass-dropdown__trigger" onClick={() => setCaptionLangOpen(!captionLangOpen)} type="button">
                  <span>{LANGUAGES.find((l) => l.code === captionLang)?.label}</span>
                  <span className="material-symbols-outlined">{captionLangOpen ? 'expand_less' : 'expand_more'}</span>
                </button>
                {captionLangOpen && (
                  <div className="acp-glass-dropdown__menu">
                    {LANGUAGES.map((l) => (
                      <button key={l.code} className={`acp-glass-dropdown__option ${captionLang === l.code ? 'acp-glass-dropdown__option--selected' : ''}`} onClick={() => { setCaptionLang(l.code); setCaptionLangOpen(false); }} type="button">{l.label}</button>
                    ))}
                  </div>
                )}
              </div>
            </div>
            <label className="acp-label">
              {t('displayStyle', 'نمط العرض')}
              <div className="acp-chips">
                {([{ k: 'standard' as const, l: t('normal', 'عادي') }, { k: 'karaoke' as const, l: t('karaoke', 'كاريوكي') }, { k: 'subtitles' as const, l: t('subtitle', 'ترجمة سفلية') }]).map((s) => (
                  <button key={s.k} className={`acp-chip ${captionStyle === s.k ? 'acp-chip--selected' : ''}`} onClick={() => setCaptionStyle(s.k)} type="button">{s.l}</button>
                ))}
              </div>
            </label>
          </>
        )}
        <div className="acp-nav-row">
          <button className="acp-btn acp-btn--ghost" onClick={() => setStep(3)} type="button">
            <span className="material-symbols-outlined" aria-hidden="true">{iconPrev}</span> {t('back', 'رجوع')}
          </button>
          <button className="acp-btn acp-btn--ghost" onClick={() => setStep(5)} type="button">{t('skip', 'تخطي')}</button>
          <button className="acp-btn acp-btn--primary" onClick={() => saveDraft(5)} disabled={saving}>
            {saving ? t('savingDots', 'حفظ...') : t('theNext', 'التالي')}
          </button>
        </div>
      </div>
    </section>
  );
}
