/**
 * Sound Platform — Audio Content Schema
 * ========================================
 * Phase:   8-E (Audio Processing Pipeline Foundation)
 * Updated: 2026-05-28
 *
 * This is the AUDIO CONTENT CORE MODULE — not generic social content.
 * `contentItems/{contentId}` is the unified storage collection, but the
 * schema is audio-first: uploaded audio, recorded audio, podcasts,
 * short clips, songs, album tracks, radio moments, competition submissions.
 *
 * Access control is determined by:
 *   - published status (visible only when status == 'published')
 *   - privacy/audience settings (owner-controlled)
 *   - moderation state (moderator-controlled)
 *   - world destination (controls PUBLISHING, NOT viewing)
 *
 * IMPORTANT: World destination does NOT gate viewing.
 *   - Plus content is readable by ANY authenticated user if published.
 *   - World controls PUBLISHING capabilities only.
 *   - Audio files are always served via signed URLs (Cloud Function).
 *
 * Phase 8-B will implement:
 *   - Audio upload/session pipeline
 *   - Signed URL generation
 *   - Waveform generation
 *   - Transcript/caption generation
 *   - Audio transcoding/normalization
 */

import type { WorldId } from './permissions';

// ─── Audio Content Status ────────────────────────────────────────────────────
//
// Lifecycle:
//   draft → readyForUpload → uploading → processing → published
//   Any state → rejected | archived | deleted
//
export type AudioContentStatus =
  | 'draft'
  | 'readyForUpload'
  | 'uploading'
  | 'processing'
  | 'published'
  | 'rejected'
  | 'archived'
  | 'deleted';

// ─── Audio Content Kind ──────────────────────────────────────────────────────
//
// Audio-first content types across all worlds:
//   general/plus:  longAudio, podcast, shortAudio
//   music:         song, albumTrack
//   radio:         radioMoment (station system only, not normal publishing)
//   tournaments:   tournamentSubmissionAudio (competition flow, not normal publishing)
//
export type AudioContentKind =
  | 'longAudio'
  | 'podcast'
  | 'shortAudio'
  | 'song'
  | 'albumTrack'
  | 'radioMoment'
  | 'tournamentSubmissionAudio';

// ─── Audio Moderation Status ─────────────────────────────────────────────────
export type AudioModerationStatus =
  | 'pending'
  | 'approved'
  | 'rejected'
  | 'flagged'
  | 'underReview';

// ─── Audio Asset Metadata ────────────────────────────────────────────────────
//
// Embedded inside AudioContentDoc as `audioAsset`.
// One audio item = one audio asset (1:1 relationship).
//
// Phase 8-B will implement:
//   - storagePath         → set by upload pipeline
//   - uploadSessionId     → tracks resumable uploads
//   - processingStatus    → set by transcoding pipeline
//   - waveformStatus      → set by waveform generator
//   - transcriptStatus    → set by transcription pipeline
//   - playbackUrl         → signed URL generated by Cloud Function
//
export interface AudioAssetMeta {
  /** Unique asset identifier (server-generated) */
  assetId: string;

  /** Cloud Storage path — NEVER exposed to client directly */
  storagePath?: string;

  /** Original file name from upload */
  originalFileName?: string;

  /** MIME type (e.g. 'audio/mpeg', 'audio/wav', 'audio/aac') */
  mimeType?: string;

  /** File size in bytes */
  sizeBytes?: number;

  /** Duration in milliseconds */
  durationMs?: number;

  // ── Processing pipeline fields (Phase 8-B) ───────────────────────────────

  /** Waveform generation status */
  waveformStatus?: 'pending' | 'processing' | 'done' | 'failed';
  /** Cloud Storage path to generated waveform data */
  waveformPath?: string;

  /** Transcript/caption generation status */
  transcriptStatus?: 'pending' | 'processing' | 'done' | 'failed';
  /** Cloud Storage path to generated transcript */
  transcriptPath?: string;

  /** Overall audio processing status */
  processingStatus?: 'pending' | 'processing' | 'done' | 'failed';
  /** Error message if processing failed */
  processingError?: string;

  /**
   * Playback URL — always a signed URL generated by Cloud Function.
   * NEVER stored permanently; generated on demand.
   * This field exists as a placeholder for the callable response shape.
   */
  playbackUrl?: string;

  // ── Source & Upload tracking (Phase 8-B) ──────────────────────────────────

  /** How the audio was acquired */
  sourceType?: 'recorded' | 'uploaded';

  /** Client-tracked upload lifecycle */
  uploadStatus?: 'pending' | 'uploading' | 'uploaded' | 'failed';

  /** ISO timestamp of upload completion */
  uploadedAt?: string;
}

// ─── Phase 8-C Types ─────────────────────────────────────────────────────────

/** Country targeting mode */
export type CountryMode = 'all' | 'one' | 'upToFour';

/** Age suitability rating */
export type AgeSuitability = 'everyone' | 'teen' | 'mature';

/** Placement feed for content appearance */
export type PlacementFeed = 'main' | 'shorts' | 'both';

/** Playlist intent during creation */
export type PlaylistIntent = 'none' | 'existing' | 'new';

/** Full audience/privacy options */
export type AudienceType =
  | 'public'
  | 'followers'
  | 'following'
  | 'friends'
  | 'specificList'
  | 'listExcept'
  | 'selectedPeople'
  | 'onlyMe';

/** Cover image asset metadata */
export interface CoverAsset {
  sourceType?: 'uploaded' | 'camera' | 'ai' | 'default';
  storagePath?: string;
  aiProvider?: string;
  aiPrompt?: string;
  uploadedAt?: string;
}

/** Captions/subtitles setup preferences */
export interface CaptionsSetup {
  enabled: boolean;
  language?: string;
  style?: 'standard' | 'karaoke' | 'subtitles';
}

/** AutoCue (teleprompter) configuration */
export interface AutoCueConfig {
  enabled: boolean;
  scriptText?: string;
  scriptSource?: 'manual' | 'description' | 'ai' | 'imported';
  scrollSpeed?: 'slow' | 'medium' | 'fast';
  fontSize?: 'small' | 'medium' | 'large';
  readingMode?: 'lineByLine' | 'paragraphByParagraph';
  startDelaySec?: number;
  highlightCurrentLine?: boolean;
}

/** Publish behaviour toggles */
export interface PublishToggles {
  commentsEnabled?: boolean;
  giftsEnabled?: boolean;
  sharingEnabled?: boolean;
  scheduledAt?: string;
}

// ─── Phase 8-E: Processing Pipeline Types ────────────────────────────────────

/**
 * Overall content processing status.
 * Tracks the state of the server-side processing pipeline
 * after an audio item is published.
 */
export type ContentProcessingStatus =
  | 'uploaded'           // original file uploaded, no processing started
  | 'queued'             // processing queued
  | 'processing'         // actively processing
  | 'ready'              // all processing complete (real transcode done)
  | 'originalFallback'   // original is playable, real processing deferred/unavailable
  | 'partial'            // some steps done, others pending
  | 'failed';            // critical failure

/**
 * Processed/transcoded audio output metadata.
 * null/undefined until real transcoding produces an output file.
 */
export interface ProcessedAudioMeta {
  /** Cloud Storage path to processed file */
  storagePath: string;
  /** MIME type of processed audio (e.g. 'audio/aac') */
  mimeType: string;
  /** Processed file size in bytes */
  sizeBytes: number;
  /** Duration in milliseconds */
  durationMs: number;
  /** Bitrate in kbps */
  bitrate?: number;
  /** Codec name (e.g. 'aac', 'opus') */
  codec?: string;
  /** EBU R128 integrated loudness in LUFS */
  loudnessLufs?: number;
  /** ISO timestamp when processing completed */
  createdAt: string;
  /** Reference back to the original upload path */
  sourceOriginalPath: string;
}

/**
 * Waveform data — peaks array + metadata.
 * When synthetic === true, peaks are placeholder data
 * that will be replaced by real extraction later.
 */
export interface WaveformData {
  /** Waveform generation status */
  status: 'pending' | 'processing' | 'ready' | 'failed';
  /** Normalized amplitude peaks (0.0–1.0), typically 200 points */
  peaks?: number[];
  /** Number of peak points */
  pointsCount?: number;
  /** Original audio sample rate in Hz */
  sampleRate?: number;
  /** true = generated placeholder, false = real extraction from audio */
  synthetic: boolean;
  /** ISO timestamp when waveform was generated */
  generatedAt?: string;
  /** Error message if generation failed */
  error?: string;
}

/**
 * Captions processing status.
 * Separate from CaptionsSetup (which is creator intent/preferences).
 * This tracks the server-side transcription pipeline.
 */
export interface CaptionsProcessing {
  /** Transcription pipeline status */
  status:
    | 'notRequested'     // creator did not enable captions
    | 'requested'        // creator enabled captions, waiting for audio processing
    | 'queued'           // audio processing done, captions queued
    | 'processing'       // transcription in progress
    | 'ready'            // transcription complete, captions available
    | 'failed'           // transcription provider ran but failed
    | 'pendingProvider'; // no transcription provider configured
  /** Language of the transcription */
  language?: string;
  /** Caption style preference (from CaptionsSetup) */
  style?: 'standard' | 'karaoke' | 'subtitles';
  /** ISO timestamp when captions processing started */
  startedAt?: string;
  /** ISO timestamp when captions processing completed */
  completedAt?: string;
  /** ISO timestamp when transcription completed (legacy alias for completedAt) */
  generatedAt?: string;
  /** Error message if transcription failed or provider missing */
  error?: string;
  /** Machine-readable error code */
  errorCode?: string;
}

/**
 * Captions asset metadata — stored when transcription produces output.
 * null/undefined until real transcription produces captions.
 */
export interface CaptionsAsset {
  /** Cloud Storage path to captions file */
  storagePath: string;
  /** Captions file format */
  format: 'vtt' | 'srt' | 'json';
  /** Language of the captions */
  language?: string;
  /** ISO timestamp when captions were generated */
  generatedAt: string;
  /** Transcription provider name (e.g. 'google-stt', 'whisper') */
  provider?: string;
  /** Number of caption segments/cues */
  segmentsCount?: number;
}

// ─── Owner Snapshot ──────────────────────────────────────────────────────────
//
// Denormalized from publicProfiles/{uid} at publish time.
// Allows feed rendering without joining to profiles collection.
// Updated by Cloud Function if owner profile changes (Phase 8-B+).
//
export interface OwnerSnapshot {
  ownerUsername: string;
  ownerDisplayName: string;
  ownerAvatarUrl?: string;
}

// ─── Audio Content Document ──────────────────────────────────────────────────
//
// Stored in: contentItems/{contentId}
//
// This is the canonical audio content entity across all worlds.
// Each document represents one published (or in-progress) audio item.
//
export interface AudioContentDoc {
  /** Document ID (matches Firestore doc ID) */
  id: string;

  /** Firebase UID of the content owner */
  ownerUid: string;

  /** Denormalized owner info for feed rendering */
  owner: OwnerSnapshot;

  // ── Classification ─────────────────────────────────────────────────────────

  /** Target world — controls publishing permissions, NOT viewing */
  world: WorldId;

  /** Audio content kind */
  kind: AudioContentKind;

  // ── Metadata ───────────────────────────────────────────────────────────────

  title: string;
  caption?: string;
  description?: string;

  /** Category ID from admin-managed categories collection */
  categoryId?: string;
  /** Localized category label snapshot */
  categoryLabel?: string;
  /** Subcategory ID */
  subcategoryId?: string;
  /** Localized subcategory label snapshot */
  subcategoryLabel?: string;

  /** Country targeting mode (Phase 8-C) */
  countryMode?: CountryMode;
  /** Country codes when countryMode !== 'all' */
  countryCodes?: string[];
  /** @deprecated use countryMode/countryCodes instead */
  countryCode?: string;
  /** @deprecated */
  countryLabel?: string;

  /** ISO 639-1 language code */
  language?: string;

  /** User-defined tags for discovery */
  tags: string[];

  /** Age suitability (Phase 8-C) */
  ageSuitability?: AgeSuitability;

  /** Publish behaviour toggles (Phase 8-C) */
  publishToggles?: PublishToggles;

  /** Cover image asset (Phase 8-C) */
  coverAsset?: CoverAsset;

  /** Captions setup preferences (Phase 8-C) */
  captionsSetup?: CaptionsSetup;

  /** AutoCue teleprompter config (Phase 8-C) */
  autoCue?: AutoCueConfig;

  // ── Phase 8-D.2 Fields ─────────────────────────────────────────────────────

  /** Whether this is child-directed content */
  isChildContent?: boolean;

  /** Placement feed: main feed, shorts/clips, or both */
  placementFeed?: PlacementFeed;

  /** Playlist intent: none, add to existing, or create new */
  playlistIntent?: PlaylistIntent;
  /** Existing playlist ID when playlistIntent === 'existing' */
  playlistId?: string;
  /** New playlist name when playlistIntent === 'new' */
  newPlaylistName?: string;

  // ── Visibility & Status ────────────────────────────────────────────────────

  /** Audience/privacy setting: 'public' | 'followers' | 'friends' | 'onlyMe' | 'custom' */
  audience: string;

  /** Content lifecycle status */
  status: AudioContentStatus;

  /** Moderation review status (server-only writes) */
  moderationStatus: AudioModerationStatus;

  /** Explicit content flag */
  isExplicit: boolean;

  // ── Audio Asset ────────────────────────────────────────────────────────────

  /** Embedded audio asset metadata (1:1 with content item) */
  audioAsset?: AudioAssetMeta;

  // ── Processing Pipeline (Phase 8-E) ────────────────────────────────────────

  /** Overall processing pipeline status */
  contentProcessingStatus?: ContentProcessingStatus;
  /** ISO timestamp — when processing was queued/started */
  processingStartedAt?: string;
  /** ISO timestamp — when processing completed (success or failure) */
  processingCompletedAt?: string;

  /** Processed/transcoded audio output — null until real transcoding runs */
  processedAudio?: ProcessedAudioMeta;

  /** Waveform peaks data (may be synthetic placeholder) */
  waveform?: WaveformData;

  /** Captions/transcription processing status (separate from captionsSetup) */
  captionsProcessing?: CaptionsProcessing;

  /** Captions asset metadata — null until real transcription produces output */
  captionsAsset?: CaptionsAsset;

  // ── Counters (server-only writes via Cloud Functions) ──────────────────────

  listensCount: number;
  likesCount: number;
  savesCount: number;
  repostsCount: number;
  commentsCount: number;
  sharesCount: number;

  // ── Timestamps ─────────────────────────────────────────────────────────────

  /** ISO timestamp — when the content was first created */
  createdAt: string;
  /** ISO timestamp — last metadata update */
  updatedAt: string;
  /** ISO timestamp — when status became 'published' */
  publishedAt?: string;

  // ── Relations (optional, for future modules) ───────────────────────────────

  /** Parent content ID — for shorts cut from long audio */
  parentContentId?: string;
  /** Source audio ID — if derived from another audio item */
  sourceAudioId?: string;
  /** Album ID — for album tracks (music world) */
  albumId?: string;
  /** Competition ID — for tournament submissions */
  competitionId?: string;
  /** Radio station ID — for radio moments */
  radioStationId?: string;
}

// ─── Audio Draft Document ────────────────────────────────────────────────────
//
// Stored in: drafts/{uid}/drafts/{draftId}
//
// Supports the SRS rule: "Audio Information screen comes first.
// If user skips publish steps, content is saved as draft automatically."
//
// All content fields are optional because the draft starts nearly empty
// and is progressively filled through the creation wizard.
//
export interface AudioDraftDoc {
  /** Draft document ID (server-generated) */
  draftId: string;

  /** Firebase UID of the draft owner */
  ownerUid: string;

  // ── Classification (optional until publish) ────────────────────────────────

  /** Target world — optional during drafting */
  world?: WorldId;
  /** Audio content kind — optional during drafting */
  kind?: AudioContentKind;

  // ── Metadata (progressively filled) ────────────────────────────────────────

  title?: string;
  caption?: string;
  description?: string;

  categoryId?: string;
  categoryLabel?: string;
  subcategoryId?: string;
  subcategoryLabel?: string;
  countryMode?: CountryMode;
  countryCodes?: string[];
  countryCode?: string;
  countryLabel?: string;
  language?: string;
  tags?: string[];

  audience?: string;
  isExplicit?: boolean;
  ageSuitability?: AgeSuitability;
  publishToggles?: PublishToggles;
  coverAsset?: CoverAsset;
  captionsSetup?: CaptionsSetup;
  autoCue?: AutoCueConfig;

  /** Whether this is child-directed content (Phase 8-D.2) */
  isChildContent?: boolean;
  /** Placement feed (Phase 8-D.2) */
  placementFeed?: PlacementFeed;
  /** Playlist intent (Phase 8-D.2) */
  playlistIntent?: PlaylistIntent;
  /** Existing playlist ID (Phase 8-D.2) */
  playlistId?: string;
  /** New playlist name (Phase 8-D.2) */
  newPlaylistName?: string;

  // ── Draft Status ───────────────────────────────────────────────────────────

  /** Draft lifecycle: 'draft' (editing) or 'readyForUpload' (info complete) */
  status: 'draft' | 'readyForUpload';

  /** Links to published contentItem if editing an existing item */
  targetContentId?: string;

  /** Audio asset ID if audio has been associated (Phase 8-B) */
  audioAssetId?: string;

  /** Embedded audio asset metadata — attached after recording/upload (Phase 8-B) */
  audioAsset?: AudioAssetMeta;

  /** UI creation wizard step tracker — e.g. 'info', 'record', 'effects', 'publish' */
  currentStep?: string;

  // ── Timestamps ─────────────────────────────────────────────────────────────

  createdAt: string;
  updatedAt: string;
  lastSavedAt: string;
}

// ─── Callable Request/Response Types ─────────────────────────────────────────

/** Request payload for createAudioDraft callable */
export interface CreateAudioDraftRequest {
  world?: WorldId;
  kind?: AudioContentKind;
  title?: string;
  caption?: string;
  description?: string;
  categoryId?: string;
  categoryLabel?: string;
  countryCode?: string;
  countryLabel?: string;
  language?: string;
  tags?: string[];
  audience?: string;
  isExplicit?: boolean;
}

/** Response payload for createAudioDraft callable */
export interface CreateAudioDraftResponse {
  draftId: string;
}

/** Request payload for updateAudioDraft callable */
export interface UpdateAudioDraftRequest {
  draftId: string;
  world?: WorldId;
  kind?: AudioContentKind;
  title?: string;
  caption?: string;
  description?: string;
  categoryId?: string;
  categoryLabel?: string;
  subcategoryId?: string;
  subcategoryLabel?: string;
  countryMode?: CountryMode;
  countryCodes?: string[];
  countryCode?: string;
  countryLabel?: string;
  language?: string;
  tags?: string[];
  audience?: string;
  isExplicit?: boolean;
  ageSuitability?: AgeSuitability;
  publishToggles?: PublishToggles;
  coverAsset?: CoverAsset;
  captionsSetup?: CaptionsSetup;
  autoCue?: AutoCueConfig;
  isChildContent?: boolean;
  placementFeed?: PlacementFeed;
  playlistIntent?: PlaylistIntent;
  playlistId?: string;
  newPlaylistName?: string;
  currentStep?: string;
  /** Audio asset metadata — attached after upload completes (Phase 8-B) */
  audioAsset?: AudioAssetMeta;
}

/** Response payload for updateAudioDraft callable */
export interface UpdateAudioDraftResponse {
  updatedAt: string;
}

/** Request payload for publishAudioContent callable */
export interface PublishAudioContentRequest {
  draftId: string;
  /** If true, delete the draft after successful publish */
  deleteDraftAfterPublish?: boolean;
}

/** Response payload for publishAudioContent callable */
export interface PublishAudioContentResponse {
  contentId: string;
  status: AudioContentStatus;
}

// ─── Phase 8-D/8-E — Audio Playback Types ───────────────────────────────────

/** Request payload for getAudioPlaybackUrl callable */
export interface GetAudioPlaybackUrlRequest {
  contentId: string;
}

/** Response payload for getAudioPlaybackUrl callable (Phase 8-E enriched) */
export interface GetAudioPlaybackUrlResponse {
  /** The content item ID */
  contentId: string;
  /** Temporary signed URL for audio playback — undefined if not playable */
  playbackUrl?: string;
  /** ISO timestamp when the signed URL expires */
  expiresAt?: string;
  /** MIME type of the audio file */
  mimeType?: string;
  /** Duration in milliseconds (if known) */
  durationMs?: number;
  /** How the audio was acquired */
  sourceType?: 'recorded' | 'uploaded';

  // ── Phase 8-E enrichments ─────────────────────────────────────────────────

  /** Whether the URL points to processed master, original upload, or nothing */
  source: 'processed' | 'original' | 'none';
  /** Overall content processing pipeline status */
  processingStatus?: ContentProcessingStatus;
  /** Waveform data (peaks + metadata) if available */
  waveform?: WaveformData;
  /** Captions processing status */
  captionsStatus?: CaptionsProcessing['status'];
}

// ─── Live Session Document (unchanged from Phase 4-H-1) ──────────────────────
//
// Stored in: liveSessions/{sessionId}
// Not part of Phase 8-A audio content module.
//
export interface LiveSessionDoc {
  id: string;
  hostUid: string;
  /** World this session is hosted in — General (open) or Plus (requires plus_creator) */
  world: 'general' | 'plus';
  title: string;
  status: 'scheduled' | 'live' | 'ended' | 'archived' | 'cancelled';
  speakerLimit: number; // Admin-configurable
  listenerCount: number;
  scheduledAt?: string;
  startedAt?: string;
  endedAt?: string;
  createdAt: string;
}
